spring:
  application:
    name: jwt

  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      cache:
        ttl: 2

server:
  port: 8080

jwt:
  issuer: jkw5033@gmail.com
  secret_key: PeuXozVJvCOXn0u8n8nKw6TI2VLsgIwmcjgXqpR8Miw=

